[package]
name = "benchmarks"
version = "0.1.0"
edition = "2024"

[features]
default = []
pg_query = ["dep:pg_query"]
pg_raw_parse = ["dep:pg_raw_parse"]

[dependencies]
criterion = { version = "0.8.2", default-features = false }
pg_query = { version = "6.1.1", optional = true }
pg_raw_parse = { path = "../", optional = true }

[[bin]]
name = "benchmarks"
path = "src/main.rs"
bench = true
harness = false
